title: Firechip
author:
  name: Alexander Salas Bastidas
  email: ajsb85@firechip.dev
description: > # this means to ignore newlines until "show_excerpts:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: firechip
    github: firechip
    # devto: firechip
    # dribbble: firechip
    # facebook: firechip
    # flickr:   firechip
    # instagram: firechip
    # linkedin: firechip
    # pinterest: firechip
    # youtube: firechip
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: firechip
    # microdotblog: firechip
    # keybase: firechip
    # Mastodon instances
    # mastodon:
    # - username: firechip
    #   instance: example.com
    # - username: firechip
    #   instance: example.com
    # GitLab instances
    # gitlab:
    # - username: firechip
    #   instance: example.com
    # - username: firechip
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.md

# Build settings
theme: firechip

plugins:
  - jekyll-feed
  - jekyll-seo-tag
