#!/bin/sh

set -e

DEBIAN_FRONTEND=noninteractive

USERNAME=vscode
USER_UID=1000
USER_GID=$USER_UID

groupadd --gid $USER_GID $USERNAME
useradd -s /bin/bash --uid $USER_UID --gid $USER_GID -m $USERNAME

apt-get update
apt-get install -y sudo
apt-get autoremove -y
apt-get clean -y
rm -rf /var/lib/apt/lists/*

cp /root/.gitconfig /home/$USERNAME/.gitconfig

echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME
chmod 0440 /etc/sudoers.d/$USERNAME
chown -R $USERNAME:$USERNAME .
chown -R $USERNAME:$USERNAME .git
chown -R $USERNAME:$USERNAME /home/$USERNAME/.gitconfig

chmod -R 775 .git
chmod -R 775 /home/$USERNAME/.gitconfig

sudo -s -u $USERNAME

DEBIAN_FRONTEND=dialog

